version: "3"
services:
  mysql:
    image: mysql:8.0.33
    platform: linux/amd64
    command: >-
      mysqld
      --default-authentication-plugin=mysql_native_password
    tmpfs:
      - /var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3316:3306